services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DIALECT: mariadb
      DB_PORT: 3306
      DB_NAME: spring
      DB_USER: db_user
      DB_PASSWORD: db_password
      # BUCKET_HOST: minio
      # BUCKET_PORT: 9000
      # BUCKET_ACCESS_KEY: minioadmin
      # BUCKET_ACCESS_SECRET: minioadminpw
      # BUCKET_NAME: files
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db
      # - minio

  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

  # MinIO-Service
  # minio:
  #   image: bitnami/minio:latest
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadminpw
  #     MINIO_DEFAULT_BUCKETS: files
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio:/data
  #   networks:
  #     - app

volumes:
  db-data:
  # minio:

networks:
  app:
