version: '3.8'

services:
  mariadb:
    image: mariadb:11.1
    container_name: bweng-backend
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: spring
      MARIADB_USER: db_user
      MARIADB_PASSWORD: db_password
    ports:
      - "3306:3306"